plugins {
    eclipse
    `eclipse-wtp`
    idea
    announce
    `build-announcements`
    antlr
    `compare-gradle-builds`
    `build-init`
    wrapper
    checkstyle
    codenarc
    findbugs
    jdepend
    pmd
    `help-tasks`
    `project-report`
    `project-reports`
    ear
    scala
    `ivy-publish`
    jacoco
    envjs
    jshint
    rhino
    assembler
    c
    cpp
    `objective-c`
    `objective-cpp`
    `windows-resources`
    `maven-publish`
    maven
    osgi
    play
    `java-gradle-plugin`
    application
    distribution
    java
    `java-library`
    `java-library-distribution`
    groovy
    war
    publishing
    `build-dashboard`
    signing
    `junit-test-suite`
    cunit
    `google-test`
}

val clean: org.gradle.api.tasks.Delete by tasks
clean.delete("buildSrc")
